### ISSUE TITLE
Correctly display Atlantis items

### ISSUE THREAD

**Issue by KuniXl** [EtienneLamoureux/TQVaultAE#385] opened 2021-08-19 18:28 UTC
![2021-08-19 20_25_35-TQVaultAE 3 8 0 0](https://user-images.githubusercontent.com/13101492/130124022-094b6d08-eb59-4016-9cb3-4fecea14f0cf.png)

game-version: v2.10
tqvault-version: 3.8.0.0

As you can see ALL Atlantis items are not being displayed correctly. Non-atlantis items work fine.

**Comment by KuniXl** [comment] 2021-08-19 18:30
btw. if you switch back to v3.9, start the game once and open tqvault --> items are displayed correctly

**Comment by hguy** [comment] 2021-08-22 23:04
Could you share one of these files?

**Comment by KuniXl** [comment] 2021-08-23 07:49
Sure I can:
[sample.vault.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/7030050/sample.vault.txt)
remove ".txt" after downloading. Github doesn't support ".vault"

btw I resolved the issue by downloading Titan Quest v2.9 and linking TQVault to the v2.9 version. Afterward, I've downloaded TQv2.10. If you link TQVault to v2.10 it will display all Atlantis items like in the picture. My guess is that TQVault uses data from the game folder and v2.10 does something differently than v2.9.

**Comment by hguy** [comment] 2021-08-24 19:57
I can't reproduce it on my machine using a fresh install of TQVault 3.8.
The game is still v2.9 on Steam (not v2.10).  What version are you using ? 
![image](https://user-images.githubusercontent.com/31834707/130680887-a59bd267-002e-4d06-b1b5-2564ef112241.png)

**Comment by KuniXl** [comment] 2021-08-24 22:48
look at my first post. the problem only happens if you use titan quest v2.10

**Comment by hguy** [comment] 2021-08-25 06:44
> look at my first post. the problem only happens if you use titan quest v2.10

Yes but v2.9 (Steam) is older than v2.10. So where did you get (platforme) that latest version ?

**Comment by KuniXl** [comment] 2021-08-25 10:11
on Steam
![image](https://user-images.githubusercontent.com/13101492/130772204-62a4bcc0-8ccd-4390-bcba-5c5fac4776f3.png)
the publicbeta - version is v2.10

**Comment by Cristi80** [comment] 2021-08-28 01:39
> ![2021-08-19 20_25_35-TQVaultAE 3 8 0 0](https://user-images.githubusercontent.com/13101492/130124022-094b6d08-eb59-4016-9cb3-4fecea14f0cf.png)
> 
> game-version: v2.10
> tqvault-version: 3.8.0.0
> 
> As you can see ALL Atlantis items are not being displayed correctly. Non-atlantis items work fine.

Hey there im the same problem but im using a mod and me thinks thats the problem:
https://steamcommunity.com/sharedfiles/filedetails/?id=2045473788

If anyone can look in to it and would be greatly appreciated!
![a few bug fixes](https://user-images.githubusercontent.com/47424326/131202240-0c66fcdf-0f0b-4836-8731-058d4368f29f.png)

**Comment by hguy** [comment] 2021-08-28 08:04
> > ![2021-08-19 20_25_35-TQVaultAE 3 8 0 0](https://user-images.githubusercontent.com/13101492/130124022-094b6d08-eb59-4016-9cb3-4fecea14f0cf.png)
> > game-version: v2.10
> > tqvault-version: 3.8.0.0
> > As you can see ALL Atlantis items are not being displayed correctly. Non-atlantis items work fine.
> 
> Hey there im the same problem but im using a hard mod and me thinks thats the problem:
> https://steamcommunity.com/sharedfiles/filedetails/?id=2045473788
> 
> If anyone can look in to it and would be greatly appreciated! (TQ AE GOG v2.9)


Have you selected your mod in configuration before loading your character in TQVault? (Custom Map setting)

![image](https://user-images.githubusercontent.com/31834707/131211100-ee3927b9-4373-42c0-af05-64a3c73abf94.png)

**Comment by KuniXl** [comment] 2021-08-28 21:28
![image](https://user-images.githubusercontent.com/13101492/131231432-ed060813-f8a8-4da7-832a-4ed878c608c6.png)
No.

**Comment by KuniXl** [comment] 2021-08-28 21:28
Which mod?

**Comment by hguy** [comment] 2021-09-06 09:23
See my answer about "Hard Mod" here #387.

**Comment by zemunac62** [comment] 2021-09-29 13:28
so,  what's the solution for  KuniXl commented on Aug 19?
same problems with my vault 3.8.0.0.
using TQ v 2.10

**Comment by KuniXl** [comment] 2021-09-29 14:10
My solution was:
1. Download TQ 2.9 (just not 2.10)
2. Copy the game folder somewhere
3. Change the "TQ Game PAth" and IT Game Path" to the 2.9 folder
4. Download 2.10 
5. Enjoy that TQVault displays everything correct, while being able to play 2.10

**Comment by zemunac62** [comment] 2021-09-29 17:32
can't find TQ v2.9.
 only 2.9 update-PLAZA

**Comment by KuniXl** [comment] 2021-09-29 18:10
I guess that should be right.

**Comment by zemunac62** [comment] 2021-09-29 19:02
my TQ 2.10 is Titan.Quest.Anniversary.Edition.Atlantis.v2.10-P2P
it's not PLAZA.

**Comment by zemunac62** [comment] 2021-09-29 19:05
just don't have what to update with 2.9 update-PLAZA

**Comment by Ninakoru** [comment] 2021-12-06 18:17
They updated the texture file format for Atlantis and the new Expansion, this happens on the 2.10 version, I fixed it along with the new DLC support in a merge pending of approval, you can test it yourself if you have the official 3.8.0 here:

https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST

**Comment by zemunac62** [comment] 2021-12-06 19:47
i can't open this ;(((

    On Monday, December 6, 2021, 07:18:11 PM GMT+1, Alejandro ***@***.***> wrote:  
 
 


They updated the texture file format for Atlantis and the new Expansion, this happens on the 2.10 version, I fixed it along with the new DLC support in a merge pending of approval, you can test it yourself if you have the official 3.8.0 here:

https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ninakoru** [comment] 2021-12-06 20:45
Is a github public page, not sure what are you troubling with, the download is a standard ZIP.

**Comment by Smaulfrey** [comment] 2021-12-07 13:32
Ninakoru, thank you! Confirmed this fixes the Atlantis bug! That was driving me nuts. Anyone else, just download ZIP provided and overwrite existing files (this is NOT a standalone installation; requires TQVaultAE already installed).

**Comment by Ninakoru** [comment] 2021-12-07 16:53
Good to know, I updated the build to also allow preview of characters with the new class (Neidan):

https://github.com/Ninakoru/TQVaultAE/releases/tag/3.8.0-TEST2

**Comment by Ninakoru** [comment] 2022-01-01 21:13
Please don't use the release on the previous post, use the latest official instead.

@EtienneLamoureux I think you can close this one too.

**Closed** 2022-01-02 18:11 UTC
Labels: bug, help reproduce
