### ISSUE TITLE
3.0.0 bug, can't see some of the characters storage

### ISSUE THREAD

**Issue by AvKy** [EtienneLamoureux/TQVaultAE#135] opened 2019-06-03 12:52 UTC
Got a problem with the newest version, basically it reads all the files without any errors, but the window cuts some part of the storage area and i can't see my items. Also can't make the window any wider, as soon as i let the lmb go it goes back to the original size. Maybe it's my laptops fault, any idea how to fix it?
![Bez tytułu](https://user-images.githubusercontent.com/51324377/58803584-2af7ea80-8610-11e9-9c41-55be1cff68f5.png)

**Comment by EtienneLamoureux** [comment] 2019-06-03 13:24
Thanks for reporting, will be fixed in the next release. 

Duplicate of #118

**Closed by EtienneLamoureux** 2019-06-03 13:24 UTC
