### ISSUE TITLE
Reading Errors

### ISSUE THREAD

**Issue by DarkEviL88** [EtienneLamoureux/TQVaultAE#112] opened 2019-05-12 01:24 UTC
![err1](https://user-images.githubusercontent.com/50534207/57576624-50b92600-748e-11e9-8fca-57bb062f5a64.png)
![err2](https://user-images.githubusercontent.com/50534207/57576625-531b8000-748e-11e9-87c7-cb42e1ed08a9.png)
My save files if needed:
https://drive.google.com/file/d/1uAGo88eYmmK9sFyAJuAqbz_w844iYm8p/view?usp=sharing

**Comment by selquest** [comment] 2019-05-12 06:58
Duplicate of #107

**Comment by EtienneLamoureux** [comment] 2019-05-12 18:13
Thanks for reporting. We're working on fixing TQVaultAE as the new Atlantis expansion changed things for everyone, whether you have the latest xpack or not. 

We'll fix this as part of #107

**Closed by EtienneLamoureux** 2019-05-12 18:13 UTC
