### ISSUE TITLE
Search button results in failure (FormatException)

### ISSUE THREAD

**Issue by GinSnob** [EtienneLamoureux/TQVaultAE#236] opened 2019-10-04 18:49 UTC
In TQ Vault 3.3 when I click the "Search" button and then put in text like "elysium" (did not put quotes in actual search) I get a FormatException error.

Screenshot:
![TQV_Search_Error](https://user-images.githubusercontent.com/3659524/66232069-e1420e00-e69c-11e9-81ec-dea182926dee.PNG)

Log:
[TQVaultAE_2019.10.04.txt](https://github.com/EtienneLamoureux/TQVaultAE/files/3691891/TQVaultAE_2019.10.04.txt)

**Comment by EtienneLamoureux** [comment] 2019-10-05 12:35
Duplicate of #233

**Closed by EtienneLamoureux** 2019-10-05 12:35 UTC
