### ISSUE TITLE
TQVaultAE_3.0.0.exe doesn't start

### ISSUE THREAD

**Issue by moststandarduser** [EtienneLamoureux/TQVaultAE#145] opened 2019-06-13 20:05 UTC
Hi there,

I downloaded the 3.0.0 version (also tried 3.0.0-alpha with same result) and after I extract everything, when I click on the .exe I get an error message:

"TQVaultAE has stopped working. Hang on while Windows reports the problem to Microsoft."

After the error message disappears, the screen goes back to what it was before and the program doesn't start.

I am playing TQ AE with Ragnarök and Atlantis DLCs via Steam. I used the TQVault 3.0.0-alpha version until today with no problems - I didn't change any settings on my computer, but it suddenly just stopped working. When it did, I deleted everything related to TQVault and downloaded the 3.0.0 version but I am getting the same message. 

Can you please try to help? I've used this tool for so long, I wouldn't know what to do without it!

Thanks a lot!

**Comment by EtienneLamoureux** [comment] 2019-06-14 12:42
Does the program produce a log or debug file in the folder it's located in?

**Comment by moststandarduser** [comment] 2019-06-14 13:54
No new files are created in the folder by trying to start the program.
The tqdebug.txt file that is part of the download by default also doesn't change. 

I don't know if this helps, but the error occurred after I installed and then uninstalled an earlier TQVault version (2.11). Please don't ask why I did that, but I don't see how this should have caused this error, especially since I re-downloaded the 3.0.0

**Comment by EtienneLamoureux** [comment] 2019-06-14 13:57
Ah, classic!

Follow the steps of the 4th question in [our FAQ](https://github.com/EtienneLamoureux/TQVaultAE/blob/master/README.md#troubleshooting-and-faq).

**Comment by moststandarduser** [comment] 2019-06-14 14:08
Unfortunately, this is not it - I already tried everything in the FAQs before raising a new issue...
When I press enter after typing regsvr32 /u VXPLib.dll it creates the following error (I translated from my local language):

"Error loading the module VXPLib.dll.
Please ensure that the binary file is saved at this path, or debug the file, to eliminate problems with the binary file or DLL-files.
The specified module could not be found."

**Comment by EtienneLamoureux** [comment] 2019-06-14 14:10
Just to make sure: you ran that command in an administrator console?

**Comment by moststandarduser** [comment] 2019-06-14 14:11
Yes

**Comment by moststandarduser** [comment] 2019-06-15 06:51
Looks like this is the same as Issue #121 
Not sure how this helps, but I guess you could say the bug has been reproduced now...

**Comment by EtienneLamoureux** [comment] 2019-06-15 16:13
Well, "reproduced" is for when we have steps that can replicate the problem on our development environment. But since it's the same issue it's most likely the same problem. I'll close this one as duplicate, you can follow #121.

**Closed by EtienneLamoureux** 2019-06-15 16:13 UTC
Labels: bug, help reproduce
