### ISSUE TITLE
Error on Divitiacus' Protective Waeve

### ISSUE THREAD

**Issue by Vazirazi** [EtienneLamoureux/TQVaultAE#239] opened 2019-10-05 18:17 UTC
Hi there is an error bug when i try to select  item "Divitiacus' Protective Waeve". 

![20191005201315_1](https://user-images.githubusercontent.com/23178479/66259055-fa39e480-e7ac-11e9-89ef-33c6f9854880.jpg)

![1](https://user-images.githubusercontent.com/23178479/66259060-045be300-e7ad-11e9-85ee-87c770a4371f.PNG)

![2](https://user-images.githubusercontent.com/23178479/66259062-09b92d80-e7ad-11e9-9772-42096ab068cc.PNG)

**Comment by EtienneLamoureux** [comment] 2019-10-05 18:29
Duplicate of #233

**Closed by EtienneLamoureux** 2019-10-05 18:29 UTC
