### ISSUE TITLE
Improve amulet display in equipment panel.

### ISSUE THREAD

**Issue by ejfudd** [EtienneLamoureux/TQVaultAE#306] opened 2020-04-15 02:19 UTC
Now that the game handles two different sizes of amulets, the equipment panel display should center the smaller items in the larger amulet slot.  Right now the amulet slot is still a 1x1 slot with the new 2x1 torcs being overdraw into an adjacent cell.

Recommend to center the 1x1 amulets in the equipment panel slot and adjust the mouse detection of the slot so that the highlighting is done correctly and the tooltip properly shows in the correct spot.

**Comment by EtienneLamoureux** [comment] 2020-04-15 14:57
Yes, great.

Duplicate of https://github.com/EtienneLamoureux/TQVaultAE/issues/128

**Closed by EtienneLamoureux** 2020-04-15 14:57 UTC
