### ISSUE TITLE
Window layout issues on some scaling settings

### ISSUE THREAD

**Issue by DarkLance69** [EtienneLamoureux/TQVaultAE#118] opened 2019-05-16 02:13 UTC
I cannot view most of the right half of the the TQVault (Inventory, stash, etc.) as they are partially outside of the window. Changing the window size does nothing. 
<img width="960" alt="what" src="https://user-images.githubusercontent.com/26020802/57821472-7ae83d80-7745-11e9-8893-7109e694dbb5.png">

**Comment by ridderzwaard** [comment] 2019-05-16 04:51
same problem here, i cant see my 2nd weapon and rings too
and i have the latest TQVault version but it say 2.6.0.0 
help

**Comment by Nagaira** [comment] 2019-05-16 11:25
Yes, I have the same problem. I thought it could be related to the screen settings, but not.
I have the last version TQVault 3.0

**Comment by EtienneLamoureux** [comment] 2019-05-16 19:48
@Nagaira @ridderzwaard @DarkLance69 Thanks for reporting. 

Could any of you provide us with your resolution, windows version and windows scaling option?

**Comment by EtienneLamoureux** [comment] 2019-05-16 19:49
This problem has also been reported by other users from other forums. It should be a priority to anyone willing to fix bugs.

**Comment by Ninakoru** [comment] 2019-05-17 00:13
Can't reproduce the problem. Maybe two screens?

**Comment by ridderzwaard** [comment] 2019-05-17 00:41
my monitor reso: 1366 768 and win 10
when I installed tqvault version 3 and try to open it everything looked normal
but after that i cant see my 2nd weapon ,rings, 3 extra backpack , and minimize/maximize X button
double click top of the window for full screen :
![Untitled](https://user-images.githubusercontent.com/50690285/57895671-10cfb580-7877-11e9-9c2f-76bd513828c1.png)

**Comment by DarkLance69** [comment] 2019-05-17 02:47
> @Nagaira @ridderzwaard @DarkLance69 Thanks for reporting. What happens when you manually resize the window or use the full-size button at the top right (next to minimize and the red x)?
> 
> Could any of you provide us with your resolution, windows version and windows scaling option?

resizing the screen doesnt help as the character and inventory sections are still not in place.

My monitor's resolution is 1920 by 1080, windows 10, with a scale of 150 percent. maybe i installed it wrong?

**Comment by Nagaira** [comment] 2019-05-17 11:32
Hi, my screen resolution is 1920x1080, scale (recomended) 125%. I have changed the scale, but nothing happens. And I'm using Windows 10.
I'm having the same problem as @ridderzwaard. I see the vaults but not the right side nor the bottom.
I cannot resize manually, as I just see only the first button, which only minimize the window.

![Problemas](https://user-images.githubusercontent.com/50698990/57925219-bb5fcc80-78a7-11e9-994c-1c35333bebab.JPG)

**Comment by Slaywright** [comment] 2019-05-17 13:43
This is caused by the windows DPI scaling (found in the Display Settings under Scale and Layout as "Change the size of text, apps and other items" in the neweset version, it was specifically called DPI scaling in earlier versions and I think was in a menu screen of its own?).

A fast fix would be tell windows not to DPI scale the application usually (through the compatibility settings) but in my case this just creates a worse mess, and I presume the problem is easy enough to fix once located.

Now, I'm not really a coder these days so I won't even attempt it lest I break all in the process, and someone who knows the code already can probably find what's up much faster. My thinking is the scaling applied to different elements is somehow using a different, well, scale, thus having the whole scaled up by the Windows scaling has varying results on different items.

I don't know if it's the width and height of of the main vault and the player inventory forms or the location of the two, but whichever decides where those two elements go is getting multiplied needlessly (see the 125% vs 150% screenshots above have different layouts) and thus sends the player inventory and the equipped intems/stash panels out of frame.

So, if it indeed is easy to get to, whatever scaling factor is used for the elements themselves should also be used for setting the position of the player inventory and the equipped items/stash, whether it is a position of the panel or the space the other panels take that scales here. I would suspect it is the former since the "Character:" label is also on an adventure, but the main vault panel seems to be aligned correctly, as does the "Vault:" label. Either these two have a non-scalable position (0, 0?) within their parent or their position scaling is actually working.

But as I said, not really a coder so takes me a good while to find this in the code, should I ever do.

**Comment by EtienneLamoureux** [comment] 2019-05-17 14:35
Thanks a look for the feedback

**Comment by Ninakoru** [comment] 2019-05-17 20:19
I changed the scaling to 125% and I get it cropped just like @Nagaira ...

**Comment by Ninakoru** [comment] 2019-05-18 02:50
Finally got it working properly. The fix is on #116

**Comment by DarkLance69** [comment] 2019-05-18 03:19
How do i download the fix?

**Comment by Ninakoru** [comment] 2019-05-18 03:31
You have to wait for the owner to properly review and accept the changes, then make a new release. Sorry.

**Comment by EtienneLamoureux** [comment] 2019-05-18 05:39
It'll get in eventually, no worries!

**Comment by ridderzwaard** [comment] 2019-05-18 09:36
thanks for your hard work guys

**Comment by Nagaira** [comment] 2019-05-18 13:22
Yes, thanks for your efforts and great job.

By the way, not sure what I settings have changed, but now, I can almost the complete vault.
![CapturaVault 2](https://user-images.githubusercontent.com/50698990/57970363-b6228080-7980-11e9-9e4c-262a3219b0db.JPG)

**Comment by Ninakoru** [comment] 2019-05-18 13:59
Just to narrow down the issue, the main program window is 1350 pixels wide and 910 pixels height. If your resolution is lower than that or the DPI scaling (in the windows 10: display settings > Scale and layout) makes the initial window size doesn't fit in your screen, the initial resize mess things up. Will be fully fixed in the next update if it gets approved.

**Closed** 2019-05-21 08:46 UTC
Labels: bug

**Comment by EtienneLamoureux** [comment] 2019-06-08 00:51
@DarkLance69 @Nagaira @clomaka @EchoC4 @AvKy @ridderzwaard You guys might be interested in the [new stable release](https://github.com/EtienneLamoureux/TQVaultAE/releases/tag/3.0.0), which should fix your problem!

**Comment by clomaka** [comment] 2019-06-08 17:49
works well on my laptop; thanks!
