### ISSUE TITLE
How to fix "This may be caused by a bad language or game path setting"?

### ISSUE THREAD

**Issue by Visurient** [EtienneLamoureux/TQVaultAE#393] opened 2021-09-26 12:44 UTC
"Value cannot be null.

This may be caused by a bad language or game path setting. 
Would you like to restart TQVault?"

I have been everywhere on the web with regards to this problem and I've tried all their solutions but they don't work. I've set the correct gamepaths and turned AutoDetectGamePath to false numerous times across multiple installs, delete, reinstalls and even tried the settings on other configs like ARZ and user.config to no avail. I've been at this for hours and I've given up. I have tried disabling autodetectlanguage but not subsequently setting a specific language which i don't know how...so I'm not sure if that's the real solution to this headache or not. A few times I encountered a different error where I got a huge window opening up with whole paragraphs of code errors when I've tried to set specific gamepaths which doubly confused me.

**Comment by hguy** [comment] 2021-09-28 07:57
Could you share your logging file ?

**Comment by Ara-tq** [comment] 2021-11-04 18:58
I think I have the same Problem as Visurient, maybe I can provide you the needed details to fix this.
So I wanted to use TQvault for the first time and upon start this box pops up:

![image](https://user-images.githubusercontent.com/93734646/140401378-9691d5c5-edd0-4dee-a7d3-d764580d0dfd.png)
which means: Vault Patch not set. Using standard path. Please check vault path in Options.

Which is fine and normal I guess.
Upon the next start it looks like this:
![image](https://user-images.githubusercontent.com/93734646/140401692-cf152f12-b008-4a5b-951f-d2bf15bb2625.png)
Translates to: Error loading resources. The value cannot be NULL. Parameter name: source
...

This repeats with every start.

Logfile says:
`2021-11-04 19:48:04,355 [1] INFO  TQVaultAE.GUI.Program [(null)] - Selected TQ path d:\steam\SteamApps\common\Titan Quest Anniversary Edition
2021-11-04 19:48:04,375 [1] INFO  TQVaultAE.GUI.Program [(null)] - Selected TQIT path d:\steam\SteamApps\common\Titan Quest Anniversary Edition
2021-11-04 19:50:18,100 [1] INFO  TQVaultAE.GUI.Program [(null)] - Selected TQ path d:\steam\SteamApps\common\Titan Quest Anniversary Edition
2021-11-04 19:50:18,119 [1] INFO  TQVaultAE.GUI.Program [(null)] - Selected TQIT path d:\steam\SteamApps\common\Titan Quest Anniversary Edition
2021-11-04 19:50:23,207 [1] INFO  TQVaultAE.GUI.MainForm [(null)] - TQVaultAE Initialization !
2021-11-04 19:50:23,322 [1] DEBUG TQVaultAE.GUI.MainForm [(null)] - Config.Settings.Default.Scale changed to 1 !
2021-11-04 19:50:23,554 [1] ERROR TQVaultAE.GUI.MainForm [(null)] - resourcesLoaded = True
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   bei TQVaultAE.GUI.MainForm.LoadAllFiles()
   bei TQVaultAE.GUI.MainForm.LoadResources(BackgroundWorker worker, DoWorkEventArgs e)
   bei TQVaultAE.GUI.MainForm.BackgroundWorkerLoadAllFiles_DoWork(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)`

The paths it uses are correct.
One thing i noticed is that it created a "TQVaultData" Folder under "..\Documents\My Games\Titan Quest", but the game actually uses "..\Documents\My Games\Titan Quest - Immortal Throne", so maybe that's the problem.
Hope that helps, let me know if you need further info.

**Comment by Ara-tq** [comment] 2021-11-05 17:43
I fiddled around a bit more and think i got a solution.
Between the 2 Messages above also this popped up:
![image](https://user-images.githubusercontent.com/93734646/140551922-5d43ef3d-1108-412e-ac4d-208760bfd1f5.png)
I thought it had nothing to do with the problem and was normal on first startup and always clicked yes. 
Then I chose No and it started fine.

**Comment by hguy** [comment] 2022-08-19 22:17
@EtienneLamoureux this is also a duplicate of #279 and can be closed.

**Closed** 2022-08-20 00:26 UTC
Labels: duplicate, question
