### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Zulmamwe** [EtienneLamoureux/TQVaultAE#84] opened 2018-05-09 11:15 UTC
Just downloaded the latest release (2.5.6) and item tooltip font size is so small i can barely see anything, is there a way to change font size in settings file?

**Comment by EtienneLamoureux** [comment] 2018-10-06 23:15
@Zulmamwe What's your resolution? Are you using Windows display scaling?

**Comment by EtienneLamoureux** [comment] 2018-10-08 01:53
We did change some font in the new release (2.5.7-alpha). Check if it helps.

**Comment by ubah68** [comment] 2019-01-21 22:10
I confirm that 2.5.7 and 2.6 releases have this issue with russian language, 1366x768, windows7x64.
![tqvault font](https://user-images.githubusercontent.com/46907634/51501331-87d1d180-1de2-11e9-9ebd-300cdacf7423.png)

**Comment by Ninakoru** [comment] 2019-05-18 14:03
The problem is not the language, is that you have small resolutions! try to get the window as big as possible (maximize button on the upper right part of the window).

**Comment by hguy** [comment] 2019-07-12 12:10
The new build #194 may have fixed this by choosing an alternative font.

**Comment by EtienneLamoureux** [comment] 2019-07-12 16:01
Great, I'll add it to the next release notes.

**Comment by EtienneLamoureux** [comment] 2019-10-04 16:03
Fixed by #194

**Closed by EtienneLamoureux** 2019-10-04 16:03 UTC
Labels: question
