### ISSUE TITLE
UI Scaling issue - 3.0.0 Alpha

### ISSUE THREAD

**Issue by EchoC4** [EtienneLamoureux/TQVaultAE#134] opened 2019-05-29 17:44 UTC
The bug has already been fixed/checked in the new release? Read about #62, wondered it's status.

Same issue, program native resolution starts bigger than the screen, resulting in a obstructed/deformed UI. Attempted multiple methods(Disabling windows DPI on the program, resizing), nothing seems to work. Running on a 1366x768 screen.
![Capture-01](https://user-images.githubusercontent.com/28910188/58576207-2ac7ab80-821a-11e9-885e-03d8852e6c7a.PNG)

**Comment by RfCypher** [comment] 2019-05-29 17:58
Same here
I already try everything that i see in issues. The version 2.6 work fine, but this version dont run with atlantis.
run on 1366x768
96 dpi (100%)

**Comment by EtienneLamoureux** [comment] 2019-05-30 06:31
Duplicate of #118 
Will be fixed in the next release!

**Closed by EtienneLamoureux** 2019-05-30 06:31 UTC
