### ISSUE TITLE
New DLC for Titan Quest

### ISSUE THREAD

**Issue by KenAlin** [EtienneLamoureux/TQVaultAE#106] opened 2019-05-09 18:03 UTC
Hi,

New DLC is available for Titan Quest : https://store.steampowered.com/app/1071200

I'm currently downloading this DLC. I guess we will have to update TQVault to support the new DLC, I will update this post as soon as possible. 😄

**Comment by KenAlin** [comment] 2019-05-09 21:26
Bad news, TQ save file format has been modified with the latest patch, so updating TQ Vault for Atlantis will be a little longer than with Ragnarok .. 😥

**Comment by EtienneLamoureux** [comment] 2019-05-10 01:30
Thanks for reporting!
Duplicate of #107

**Closed by EtienneLamoureux** 2019-05-10 01:30 UTC
