### ISSUE TITLE
The program seems to lose the path of my steam libraryfolders.vdf

### ISSUE THREAD

**Issue by TrmorySpindrift** [EtienneLamoureux/TQVaultAE#96] opened 2018-10-13 18:48 UTC
### libraryfolders lost!
- Today I deleted all save files in "My game" folder including "Titan Quest ", "Titan Quest - Immortal Throne" and "Titan Quest Backup".
- After that, I restarted my game to rebuild save files.
- Unfortunately, I find that TQVaultAE not working....
- It indicated that can't find a part of this path"X:\Grim Dawn\Steam\SteamApps\libraryfolders.vdf"
- By the way, my Grim Dawn is installed in X:\Grim Dawn.(It's not downloaded from steam)
![image](https://user-images.githubusercontent.com/26647057/46908693-25527500-cf59-11e8-8af8-09721a0bc152.png)

---

- My steam libraryfolders is not in that path at all!(It's "E:\Steam\steamapps\libraryfolders.vdf")
- Then I copy my libraryfolders.vdf(file in real path) to the false path the messagebox mentioned(I created new folder "Steam" and "SteamApps")
- it worked again...
- Can anyone tell me how to fix this problem?
---
- I have debugged the code,and find the the program get a wrong steam path from a registry function
- Maybe my registry is a mess or the function is not perfect
- If there is no better idea to solve this problem, I'd like to copy the libraryfolders.vdf temporarily.

**Comment by EtienneLamoureux** [comment] 2018-10-14 00:27
This is a known problem people have with the auto-detection of the path. To fix it, tell TQVaultAE where it can find the game files manually: See [The F.A.Q.](https://github.com/EtienneLamoureux/TQVaultAE#troubleshooting-and-faq), section "**Error Loading Resources. This may be caused by a bad language or game path setting.**"

**Comment by EtienneLamoureux** [comment] 2018-10-14 00:29
Will close as a duplicate of https://github.com/EtienneLamoureux/TQVaultAE/issues/80
Fell free to keep commenting for that problem in the main issue.

**Closed by EtienneLamoureux** 2018-10-14 00:29 UTC
Labels: question
