### ISSUE TITLE
Character tab mis-aligned on Win 8.1 and/or small screens

### ISSUE THREAD

**Issue by clomaka** [EtienneLamoureux/TQVaultAE#129] opened 2019-05-23 20:14 UTC
TQVault on my laptop (running windows 8.1)  has the right side moved partly off-screen. I included a screenshot to show what it does. It displays fine on my regular pc running win10, so i'm not sure quite where the fault is coming from, but it makes most of the character tab useless. :(

![Untitled-1](https://user-images.githubusercontent.com/6282946/58282986-34ae6200-7d75-11e9-838a-f258705ea6cc.jpg)

**Comment by Alexander030** [comment] 2019-05-26 16:09
I am having the same problem only that I'm using windows 7

**Comment by EtienneLamoureux** [comment] 2019-05-30 06:30
Duplicate of #118 
Will be fixed in the next release!

**Closed by EtienneLamoureux** 2019-05-30 06:30 UTC
