### ISSUE TITLE
TQVualt not working since TQ version 2.7 launched

### ISSUE THREAD

**Issue by Ruamoko** [EtienneLamoureux/TQVaultAE#156] opened 2019-06-20 07:52 UTC
Since the latest game patch, vault is unable to load files.

**Comment by DeepThough7** [comment] 2019-06-20 08:44
Im Getting this Error message when i start TQVault

UI Thread Exception
Message : TEX magic is invalid.

Stack Trace:
   at TQVaultData.BitmapCode.LoadFromTexMemory(Byte[] data, Int32 offset, Int32 count)
   at TQVaultData.Database.LoadBitmap(String resourceId)
   at TQVaultData.Item.GetDBData()
   at TQVaultData.Item.Parse(BinaryReader reader)
   at TQVaultData.SackCollection.Parse(BinaryReader reader)
   at TQVaultData.Stash.ParseItemBlock(Int32 fileOffset, BinaryReader reader)
   at TQVaultData.Stash.ParseRawData()
   at TQVaultData.Stash.LoadFile()
   at TQVaultAE.GUI.MainForm.LoadRelicVaultStash()
   at TQVaultAE.GUI.MainForm.BackgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by herbalite** [comment] 2019-06-20 09:27
Same here. After the error mentioned above, when I open now I get an dialog 

Error reading player file.

And the detailed message contains path info and "Error parsing player file Equipment Block - 'Berserker'  where Berserker is the name of the build. When TQ Vault opens after the error message everything seems to be in order, except for the Equipment panel, which is empty

**Comment by EtienneLamoureux** [comment] 2019-06-20 14:10
Thanks for reporting everyone. 

This is a duplicate of #155, but I'll leave it open for now as to prevent more duplicates from being opened. The problem here is that the patch broke some data files
 There's not much to do on our end: we need the TQ developers to fix their faulty files.

**Comment by TheOne320** [comment] 2019-06-20 14:30
Are the corrupt data files already reported on the redmine bug tracker?

**Comment by EtienneLamoureux** [comment] 2019-06-20 17:44
@TheOne320 I haven't had a chance to check

**Closed** 2019-06-21 12:01 UTC
Labels: bug, duplicate
